/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

//! Shared post-translation compiler pipeline.
//!
//! Frontends stop after assembling a `dialect-mir` module. This module owns
//! every destructive compiler stage after that boundary so the rustc frontend
//! and the experimental frontend cannot silently diverge.

use crate::error::PipelineError;
use crate::export::{
    DeviceExternDecl, export_llvm_ir, module_uses_libdevice, render_llvm_ir, resolve_nvvm_target,
    unresolved_external_symbols, validate_nvvm_debug_support,
};
use crate::llvm_tools::LlvmToolchain;
use crate::lower::{add_device_extern_declarations, lower_to_llvm};
use crate::options::BackendOptions;
use crate::prep::{MirPreparation, prepare_mir_module};
use crate::ptx::{GeneratedPtx, generate_ptx, generate_ptx_with_toolchain};
use crate::target::detect_features_in_llvm_text;
use crate::verify::verify_operation;
use llvm_export::export::{DebugKind, NvvmIrDialect};
use pliron::context::{Context, Ptr};
use pliron::operation::Operation;
use pliron::printable::Printable;
use std::path::{Path, PathBuf};

/// Files used to publish one compiler result.
#[doc(hidden)]
#[derive(Clone, Copy, Debug)]
pub struct OutputFiles<'a> {
    /// Textual LLVM IR output.
    pub llvm_ir: &'a Path,
    /// PTX output. This remains absent for an NVVM IR result.
    pub ptx: &'a Path,
    /// Older competing artifacts to remove immediately before export.
    pub stale_before_export: &'a [PathBuf],
}

/// Legacy command-line tracing requested by the rustc frontend.
#[doc(hidden)]
#[derive(Clone, Copy, Debug, Default)]
pub struct PipelineTrace {
    /// Print compiler-stage progress.
    pub verbose: bool,
    /// Print the module before and after MIR preparation.
    pub dump_mir: bool,
    /// Print the lowered module before final verification.
    pub dump_llvm: bool,
    /// Receives trace lines and legacy diagnostics. `None` keeps the backend quiet.
    pub sink: Option<fn(&str)>,
}

impl PipelineTrace {
    fn emit(&self, message: impl AsRef<str>) {
        if let Some(sink) = self.sink {
            sink(message.as_ref());
        }
    }
}

#[derive(Clone, Copy, Debug)]
enum OutputPolicy {
    SelfContainedPtx,
    ExternalLinkAllowed { request_nvvm_ir: bool },
}

#[derive(Clone, Copy, Debug)]
enum ToolchainPolicy<'a> {
    Discover,
    Explicit(&'a LlvmToolchain),
}

/// Complete request for the shared post-translation pipeline.
#[doc(hidden)]
pub struct ModulePipelineRequest<'a> {
    device_externs: &'a [DeviceExternDecl],
    output_policy: OutputPolicy,
    backend: &'a BackendOptions,
    debug_kind: DebugKind,
    toolchain: ToolchainPolicy<'a>,
    files: OutputFiles<'a>,
    trace: PipelineTrace,
}

impl<'a> ModulePipelineRequest<'a> {
    /// Build the link-capable request used by the rustc frontend.
    #[doc(hidden)]
    pub fn for_rust_pipeline(
        device_externs: &'a [DeviceExternDecl],
        request_nvvm_ir: bool,
        backend: &'a BackendOptions,
        debug_kind: DebugKind,
        files: OutputFiles<'a>,
        trace: PipelineTrace,
    ) -> Self {
        Self {
            device_externs,
            output_policy: OutputPolicy::ExternalLinkAllowed { request_nvvm_ir },
            backend,
            debug_kind,
            toolchain: ToolchainPolicy::Discover,
            files,
            trace,
        }
    }

    pub(crate) fn for_standalone_ptx(
        backend: &'a BackendOptions,
        debug_kind: DebugKind,
        toolchain: &'a LlvmToolchain,
        files: OutputFiles<'a>,
    ) -> Self {
        Self {
            device_externs: &[],
            output_policy: OutputPolicy::SelfContainedPtx,
            backend,
            debug_kind,
            toolchain: ToolchainPolicy::Explicit(toolchain),
            files,
            trace: PipelineTrace::default(),
        }
    }
}

/// Artifact format emitted by the shared pipeline.
#[doc(hidden)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ModuleArtifactKind {
    /// Textual PTX generated by `llc`.
    Ptx,
    /// NVVM-compatible LLVM IR for a later libNVVM/nvJitLink step.
    NvvmIr,
}

/// Successful shared-pipeline result.
#[doc(hidden)]
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ModulePipelineOutput {
    /// Format written to the requested artifact files.
    pub artifact_kind: ModuleArtifactKind,
    /// Concrete target selected from explicit options, the device hint, or IR features.
    pub target: String,
    /// Messages retained for the legacy CLI to print.
    pub diagnostics: Vec<String>,
}

/// Compile an already-translated `dialect-mir` module to PTX or NVVM IR.
#[doc(hidden)]
pub fn compile_translated_module(
    ctx: &mut Context,
    module: Ptr<Operation>,
    request: &ModulePipelineRequest<'_>,
) -> Result<ModulePipelineOutput, PipelineError> {
    if request.trace.dump_mir {
        request
            .trace
            .emit("\n=== dialect-mir module (pre-verify) ===");
        request
            .trace
            .emit(format!("{}", module.deref(ctx).disp(ctx)));
    }
    if request.trace.verbose {
        request.trace.emit("\n=== Verifying dialect-mir module ===");
    }

    let promote_and_unroll = !request.debug_kind.variables_enabled();
    if request.trace.verbose {
        if promote_and_unroll {
            request
                .trace
                .emit("\n=== Running shared mem2reg + annotated loop-unroll preparation ===");
        } else {
            request
                .trace
                .emit("\n=== Skipping mem2reg (full debug keeps locals in memory) ===");
        }
    }
    prepare_mir_module(ctx, module, MirPreparation { promote_and_unroll })?;
    if request.trace.verbose {
        request.trace.emit("dialect-mir preparation successful ✓");
    }
    if request.trace.dump_mir && promote_and_unroll {
        request
            .trace
            .emit("\n=== dialect-mir module (after preparation) ===");
        request
            .trace
            .emit(format!("{}", module.deref(ctx).disp(ctx)));
    }

    // Calls need structured extern declarations before lowering so pointer
    // address spaces are preserved by the call converter.
    if !request.device_externs.is_empty() {
        if request.trace.verbose {
            request.trace.emit(format!(
                "\n=== Adding {} device extern declarations ===",
                request.device_externs.len()
            ));
        }
        add_device_extern_declarations(ctx, module, request.device_externs)?;
    }

    if request.trace.verbose {
        request
            .trace
            .emit("\n=== Lowering dialect-mir → LLVM dialect ===");
    }
    lower_to_llvm(ctx, module, !request.backend.no_fma)?;

    let needs_libdevice = module_uses_libdevice(ctx, module);
    let emit_nvvm_ir = should_emit_nvvm_ir(request.output_policy, needs_libdevice);
    let requested_nvvm_ir = matches!(
        request.output_policy,
        OutputPolicy::ExternalLinkAllowed {
            request_nvvm_ir: true
        }
    );
    if needs_libdevice && !requested_nvvm_ir && emit_nvvm_ir && request.trace.verbose {
        request.trace.emit(
            "\n=== Detected CUDA libdevice (`__nv_*`) calls; \
             auto-emitting NVVM IR (skip llc) ===",
        );
    }

    // NVVM pointer syntax depends on the target. Detect the feature floor from
    // the same pre-legalization text the ordinary PTX path would inspect.
    let automatic_features = if emit_nvvm_ir {
        let preview = render_llvm_ir(
            ctx,
            module,
            request.device_externs,
            false,
            None,
            request.debug_kind,
        )?;
        Some(detect_features_in_llvm_text(&preview))
    } else {
        None
    };

    let (nvvm_target, nvvm_dialect) = if emit_nvvm_ir {
        let target = resolve_nvvm_target(
            request.backend.target_arch.as_deref(),
            request.backend.device_arch_hint.as_deref(),
            automatic_features,
        )?;
        let dialect = if target.uses_legacy_llvm() {
            NvvmIrDialect::LegacyLlvm7
        } else {
            NvvmIrDialect::Modern
        };
        validate_nvvm_debug_support(&target, dialect, request.debug_kind)?;
        (Some(target), Some(dialect))
    } else {
        (None, None)
    };

    if let Some(dialect) = nvvm_dialect {
        if request.trace.verbose {
            if dialect == NvvmIrDialect::LegacyLlvm7 {
                request
                    .trace
                    .emit("\n=== Legalizing LLVM dialect for legacy NVVM ===");
            } else {
                request
                    .trace
                    .emit("\n=== Legalizing NVVM bit-intrinsic widths ===");
            }
        }
        nvvm_transforms::legalize_for_nvvm(ctx, module, dialect)
            .map_err(|error| PipelineError::Lowering(error.disp(ctx).to_string()))?;
    }

    if request.trace.dump_llvm {
        request.trace.emit("\n=== LLVM dialect (pre-verify) ===");
        request
            .trace
            .emit(format!("{}", module.deref(ctx).disp(ctx)));
    }
    if request.trace.verbose {
        request.trace.emit("=== Verifying LLVM dialect module ===");
    }
    verify_operation(ctx, module, "llvm module").map_err(as_lowered_verification)?;
    if request.trace.verbose {
        request.trace.emit("LLVM dialect verification successful ✓");
    }

    if matches!(request.output_policy, OutputPolicy::SelfContainedPtx) {
        let symbols = unresolved_external_symbols(ctx, module);
        if !symbols.is_empty() {
            return Err(PipelineError::UnsupportedLinking { symbols });
        }
    }

    if request.trace.verbose {
        let mode = if emit_nvvm_ir { "NVVM IR" } else { "PTX" };
        request
            .trace
            .emit(format!("\n=== Exporting to LLVM IR ({mode} mode) ==="));
    }
    remove_stale_files(request.files.stale_before_export)?;
    export_llvm_ir(
        ctx,
        module,
        request.device_externs,
        request.files.llvm_ir,
        emit_nvvm_ir,
        nvvm_dialect,
        request.debug_kind,
    )?;
    if request.trace.verbose {
        request.trace.emit(format!(
            "LLVM IR written to {}",
            request.files.llvm_ir.display()
        ));
    }

    if emit_nvvm_ir {
        if request.trace.verbose {
            let reason = if needs_libdevice {
                "libdevice present"
            } else {
                "NVVM IR requested"
            };
            request.trace.emit(format!(
                "\n=== Skipping llc ({reason}); consumer owns libNVVM/nvJitLink build ==="
            ));
        }
        return Ok(ModulePipelineOutput {
            artifact_kind: ModuleArtifactKind::NvvmIr,
            target: nvvm_target
                .expect("NVVM target was resolved before export")
                .sm(),
            diagnostics: Vec::new(),
        });
    }

    if request.trace.verbose {
        request.trace.emit("\n=== Generating PTX ===");
    }
    let generated = match request.toolchain {
        ToolchainPolicy::Discover => generate_ptx(
            request.files.llvm_ir,
            request.files.ptx,
            request.debug_kind,
            request.backend,
            request.trace.sink,
        )?,
        ToolchainPolicy::Explicit(toolchain) => GeneratedPtx {
            target: generate_ptx_with_toolchain(
                request.files.llvm_ir,
                request.files.ptx,
                request.debug_kind,
                request.backend,
                toolchain,
            )?,
            diagnostics: Vec::new(),
        },
    };
    if request.trace.verbose {
        request.trace.emit(format!(
            "✓ PTX written to {} (target: {})",
            request.files.ptx.display(),
            generated.target
        ));
    }
    Ok(ModulePipelineOutput {
        artifact_kind: ModuleArtifactKind::Ptx,
        target: generated.target,
        diagnostics: generated.diagnostics,
    })
}

fn should_emit_nvvm_ir(policy: OutputPolicy, needs_libdevice: bool) -> bool {
    match policy {
        OutputPolicy::SelfContainedPtx => false,
        OutputPolicy::ExternalLinkAllowed { request_nvvm_ir } => request_nvvm_ir || needs_libdevice,
    }
}

fn as_lowered_verification(error: PipelineError) -> PipelineError {
    match error {
        PipelineError::Verification {
            message, operation, ..
        } => PipelineError::LoweredVerification { message, operation },
        other => other,
    }
}

fn remove_stale_files(paths: &[PathBuf]) -> Result<(), PipelineError> {
    for path in paths {
        match std::fs::remove_file(path) {
            Ok(()) => {}
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
            Err(error) => {
                return Err(PipelineError::Export(format!(
                    "failed to invalidate stale CUDA artifact {}: {error}",
                    path.display()
                )));
            }
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn standalone_never_silently_switches_to_a_linkable_artifact() {
        assert!(!should_emit_nvvm_ir(OutputPolicy::SelfContainedPtx, false));
        assert!(!should_emit_nvvm_ir(OutputPolicy::SelfContainedPtx, true));
    }

    #[test]
    fn link_capable_pipeline_honors_requests_and_libdevice() {
        let automatic = OutputPolicy::ExternalLinkAllowed {
            request_nvvm_ir: false,
        };
        let requested = OutputPolicy::ExternalLinkAllowed {
            request_nvvm_ir: true,
        };
        assert!(!should_emit_nvvm_ir(automatic, false));
        assert!(should_emit_nvvm_ir(automatic, true));
        assert!(should_emit_nvvm_ir(requested, false));
    }

    #[test]
    fn final_verification_is_not_reported_as_mir_preparation() {
        let classified = as_lowered_verification(PipelineError::Verification {
            name: "llvm module".to_string(),
            message: "invalid lowered op".to_string(),
            operation: Some("llvm.bad".to_string()),
        });
        assert!(matches!(
            classified,
            PipelineError::LoweredVerification { message, operation }
                if message == "invalid lowered op" && operation.as_deref() == Some("llvm.bad")
        ));
    }
}
