; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 44/0.1.0; intrinsic ABI: v1; catalog SHA-256: 0b728aae717a7fc414a18ba59aa04644fdb3da7d5c6e7edd2eadc6f911b9d595.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

declare void @llvm.nvvm.cp.async.wait.group(i32)

define void @probe_cp_async_wait_group() {
  call void @llvm.nvvm.cp.async.wait.group(i32 3)
  ret void
}
