; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 44/0.1.0; intrinsic ABI: v1; catalog SHA-256: 0b728aae717a7fc414a18ba59aa04644fdb3da7d5c6e7edd2eadc6f911b9d595.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

declare float @llvm.nvvm.sqrt.rp.ftz.f(float)

define float @probe_sqrt_rp_ftz_f32(float %arg0) {
  %result = call float @llvm.nvvm.sqrt.rp.ftz.f(float %arg0)
  ret float %result
}
